import type { Recipe } from '../types';

export const RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Spaghetti Carbonara',
    description:
      'A classic Roman pasta dish with eggs, Pecorino Romano, pancetta and black pepper. Creamy, rich, and absolutely irresistible.',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    cuisine: 'Italian',
    difficulty: 'Medium',
    mealType: 'Dinner',
    dietTags: [],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    rating: 4.8,
    reviewCount: 1243,
    calories: 520,
    author: 'Chef Marco',
    ingredients: [
      { name: 'Spaghetti', amount: '400', unit: 'g' },
      { name: 'Pancetta', amount: '200', unit: 'g' },
      { name: 'Eggs', amount: '4', unit: 'large' },
      { name: 'Pecorino Romano', amount: '100', unit: 'g' },
      { name: 'Black pepper', amount: '2', unit: 'tsp' },
      { name: 'Salt', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      {
        step: 1,
        text: 'Bring a large pot of salted water to a boil. Cook spaghetti until al dente.',
        duration: 10,
      },
      {
        step: 2,
        text: 'Fry pancetta in a large pan over medium heat until crispy, about 5 minutes.',
        duration: 5,
      },
      {
        step: 3,
        text: 'Whisk together eggs, grated Pecorino Romano, and a generous amount of black pepper.',
      },
      { step: 4, text: 'Remove pan from heat. Add drained pasta to the pancetta and toss well.' },
      {
        step: 5,
        text: 'Add egg mixture, tossing quickly and adding pasta water to create a creamy sauce.',
        duration: 3,
      },
    ],
    nutrition: { calories: 520, protein: 24, carbs: 68, fat: 18, fiber: 3 },
    tips: [
      'Never add cream — the creaminess comes from eggs and pasta water',
      "Work fast when adding eggs so they don't scramble",
    ],
  },
  {
    id: '2',
    title: 'Avocado Toast with Poached Eggs',
    description:
      'The ultimate brunch — creamy avocado on crusty sourdough topped with perfectly poached eggs and red pepper flakes.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    cuisine: 'American',
    difficulty: 'Easy',
    mealType: 'Breakfast',
    dietTags: ['Vegetarian', 'Healthy'],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    rating: 4.6,
    reviewCount: 876,
    calories: 380,
    author: 'Emma Green',
    ingredients: [
      { name: 'Sourdough bread', amount: '4', unit: 'slices' },
      { name: 'Ripe avocados', amount: '2', unit: 'large' },
      { name: 'Eggs', amount: '4', unit: 'large' },
      { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
      { name: 'Red pepper flakes', amount: '1', unit: 'tsp' },
      { name: 'Salt & pepper', amount: '', unit: 'to taste' },
    ],
    instructions: [
      { step: 1, text: 'Toast the sourdough slices until golden and crispy.' },
      { step: 2, text: 'Mash avocados with lemon juice, salt, and pepper in a bowl.' },
      {
        step: 3,
        text: 'Bring a pot of water to a gentle simmer. Add a splash of vinegar.',
        duration: 3,
      },
      {
        step: 4,
        text: 'Poach eggs for 3–4 minutes until whites are set but yolks are runny.',
        duration: 4,
      },
      { step: 5, text: 'Spread avocado on toast, top with poached eggs and red pepper flakes.' },
    ],
    nutrition: { calories: 380, protein: 16, carbs: 32, fat: 22, fiber: 8 },
    tips: [
      'Use very fresh eggs for the best poached results',
      'Add a splash of white vinegar to the poaching water',
    ],
  },
  {
    id: '3',
    title: 'Chicken Tikka Masala',
    description:
      'Tender chicken pieces marinated in spiced yogurt, grilled and simmered in a rich, creamy tomato sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    cuisine: 'Indian',
    difficulty: 'Medium',
    mealType: 'Dinner',
    dietTags: ['Gluten-Free'],
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    rating: 4.9,
    reviewCount: 2156,
    calories: 450,
    author: 'Priya Sharma',
    ingredients: [
      { name: 'Chicken breast', amount: '700', unit: 'g' },
      { name: 'Greek yogurt', amount: '200', unit: 'g' },
      { name: 'Garam masala', amount: '2', unit: 'tbsp' },
      { name: 'Crushed tomatoes', amount: '400', unit: 'g' },
      { name: 'Heavy cream', amount: '200', unit: 'ml' },
      { name: 'Ginger garlic paste', amount: '2', unit: 'tbsp' },
      { name: 'Onion', amount: '2', unit: 'medium' },
    ],
    instructions: [
      {
        step: 1,
        text: 'Marinate chicken in yogurt, garam masala, and ginger garlic paste for at least 2 hours.',
        duration: 120,
      },
      {
        step: 2,
        text: 'Grill or broil marinated chicken until charred and cooked through.',
        duration: 15,
      },
      {
        step: 3,
        text: 'Sauté onions until golden, add spices and cook for 2 minutes.',
        duration: 10,
      },
      { step: 4, text: 'Add crushed tomatoes and simmer for 15 minutes.', duration: 15 },
      { step: 5, text: 'Add chicken and cream, simmer for 10 more minutes.', duration: 10 },
    ],
    nutrition: { calories: 450, protein: 38, carbs: 18, fat: 24, fiber: 4 },
    tips: ['Marinate overnight for best flavor', 'Use kashmiri chili for authentic color'],
  },
  {
    id: '4',
    title: 'Vegan Buddha Bowl',
    description:
      'A nourishing bowl of roasted vegetables, chickpeas, quinoa and tahini dressing — colorful, healthy and completely plant-based.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    cuisine: 'Mediterranean',
    difficulty: 'Easy',
    mealType: 'Lunch',
    dietTags: ['Vegan', 'Gluten-Free', 'Healthy'],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    rating: 4.7,
    reviewCount: 934,
    calories: 420,
    author: 'Luna Davis',
    ingredients: [
      { name: 'Quinoa', amount: '200', unit: 'g' },
      { name: 'Chickpeas', amount: '400', unit: 'g' },
      { name: 'Sweet potato', amount: '1', unit: 'large' },
      { name: 'Broccoli', amount: '200', unit: 'g' },
      { name: 'Tahini', amount: '3', unit: 'tbsp' },
      { name: 'Lemon juice', amount: '2', unit: 'tbsp' },
      { name: 'Avocado', amount: '1', unit: 'medium' },
    ],
    instructions: [
      { step: 1, text: 'Cook quinoa according to package instructions.', duration: 15 },
      {
        step: 2,
        text: 'Toss chickpeas and sweet potato with olive oil and spices. Roast at 200°C.',
        duration: 25,
      },
      { step: 3, text: 'Steam broccoli until tender-crisp.', duration: 5 },
      { step: 4, text: 'Whisk tahini with lemon juice, garlic, and water to make dressing.' },
      { step: 5, text: 'Assemble bowls with quinoa, veggies, avocado and drizzle with dressing.' },
    ],
    nutrition: { calories: 420, protein: 16, carbs: 58, fat: 16, fiber: 14 },
    tips: ['Meal prep the components ahead for quick weekday lunches'],
  },
  {
    id: '5',
    title: 'Beef Tacos al Pastor',
    description:
      'Juicy marinated pork slow-cooked with pineapple, served in warm corn tortillas with fresh toppings.',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    cuisine: 'Mexican',
    difficulty: 'Medium',
    mealType: 'Dinner',
    dietTags: ['Gluten-Free', 'Dairy-Free'],
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    rating: 4.8,
    reviewCount: 1567,
    calories: 390,
    author: 'Carlos Rivera',
    ingredients: [
      { name: 'Pork shoulder', amount: '500', unit: 'g' },
      { name: 'Pineapple', amount: '200', unit: 'g' },
      { name: 'Corn tortillas', amount: '12', unit: 'small' },
      { name: 'Achiote paste', amount: '2', unit: 'tbsp' },
      { name: 'Cilantro', amount: '1', unit: 'bunch' },
      { name: 'White onion', amount: '1', unit: 'medium' },
      { name: 'Lime', amount: '3', unit: 'pieces' },
    ],
    instructions: [
      {
        step: 1,
        text: 'Slice pork thin and marinate with achiote paste, pineapple juice for 2 hours.',
        duration: 120,
      },
      {
        step: 2,
        text: 'Cook marinated pork in a hot skillet until caramelized, 5–6 minutes per side.',
        duration: 12,
      },
      { step: 3, text: 'Grill pineapple slices until lightly charred.', duration: 5 },
      { step: 4, text: 'Warm tortillas on a dry skillet or directly over flame.', duration: 3 },
      {
        step: 5,
        text: 'Assemble tacos with pork, pineapple, cilantro, onion and squeeze of lime.',
      },
    ],
    nutrition: { calories: 390, protein: 28, carbs: 38, fat: 14, fiber: 4 },
    tips: [
      'Marinate overnight for authentic depth of flavor',
      'A spit roast is traditional but a skillet works great',
    ],
  },
  {
    id: '6',
    title: 'French Onion Soup',
    description:
      'A deeply savory, slow-cooked caramelized onion soup topped with crusty croutons and bubbling Gruyère cheese.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    cuisine: 'French',
    difficulty: 'Medium',
    mealType: 'Dinner',
    dietTags: ['Vegetarian'],
    prepTime: 15,
    cookTime: 60,
    servings: 4,
    rating: 4.7,
    reviewCount: 723,
    calories: 340,
    author: 'Sophie Laurent',
    ingredients: [
      { name: 'Yellow onions', amount: '6', unit: 'large' },
      { name: 'Beef broth', amount: '1.5', unit: 'liters' },
      { name: 'Gruyère cheese', amount: '200', unit: 'g' },
      { name: 'Baguette', amount: '1', unit: 'whole' },
      { name: 'Dry white wine', amount: '120', unit: 'ml' },
      { name: 'Butter', amount: '3', unit: 'tbsp' },
      { name: 'Thyme', amount: '4', unit: 'sprigs' },
    ],
    instructions: [
      { step: 1, text: 'Slice onions thinly. Melt butter in a heavy pot over medium-low heat.' },
      {
        step: 2,
        text: 'Cook onions, stirring occasionally, until deeply golden and caramelized.',
        duration: 45,
      },
      {
        step: 3,
        text: 'Add wine and cook until reduced. Add broth and thyme, simmer 15 minutes.',
        duration: 20,
      },
      { step: 4, text: 'Toast baguette slices. Ladle soup into oven-safe bowls.' },
      {
        step: 5,
        text: 'Top with croutons and Gruyère. Broil until cheese is bubbling and golden.',
        duration: 5,
      },
    ],
    nutrition: { calories: 340, protein: 16, carbs: 32, fat: 16, fiber: 3 },
    tips: [
      "Don't rush the caramelization — it's the soul of the dish",
      'Use a dry sherry instead of wine for a richer flavor',
    ],
  },
  {
    id: '7',
    title: 'Japanese Ramen',
    description:
      'Rich tonkotsu broth with tender chashu pork, soft-boiled eggs, noodles, and all the classic toppings.',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800',
    cuisine: 'Japanese',
    difficulty: 'Hard',
    mealType: 'Dinner',
    dietTags: ['Dairy-Free'],
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    rating: 4.9,
    reviewCount: 1892,
    calories: 580,
    author: 'Kenji Tanaka',
    ingredients: [
      { name: 'Ramen noodles', amount: '400', unit: 'g' },
      { name: 'Pork belly', amount: '500', unit: 'g' },
      { name: 'Eggs', amount: '4', unit: 'large' },
      { name: 'Pork bones', amount: '1', unit: 'kg' },
      { name: 'Soy sauce', amount: '4', unit: 'tbsp' },
      { name: 'Miso paste', amount: '3', unit: 'tbsp' },
      { name: 'Green onions', amount: '4', unit: 'stalks' },
      { name: 'Nori sheets', amount: '4', unit: 'pieces' },
    ],
    instructions: [
      {
        step: 1,
        text: 'Blanch pork bones. Simmer in fresh water for 3 hours for tonkotsu broth.',
        duration: 180,
      },
      {
        step: 2,
        text: 'Roll and tie pork belly. Braise in soy, mirin, and sake for 2 hours.',
        duration: 120,
      },
      {
        step: 3,
        text: 'Soft-boil eggs for 6 minutes. Marinate in soy tare overnight.',
        duration: 6,
      },
      { step: 4, text: 'Strain broth and season with miso and soy tare to taste.' },
      { step: 5, text: 'Cook noodles. Assemble bowls with broth, noodles, and all toppings.' },
    ],
    nutrition: { calories: 580, protein: 34, carbs: 62, fat: 22, fiber: 3 },
    tips: [
      'The broth is everything — give it the full 3 hours',
      'Marinated eggs are best made the night before',
    ],
  },
  {
    id: '8',
    title: 'Chocolate Lava Cake',
    description:
      'Warm, gooey chocolate cake with a molten center. The ultimate impressive yet simple dessert for any occasion.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800',
    cuisine: 'French',
    difficulty: 'Medium',
    mealType: 'Dessert',
    dietTags: ['Vegetarian'],
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    rating: 4.9,
    reviewCount: 2341,
    calories: 460,
    author: 'Sophie Laurent',
    ingredients: [
      { name: 'Dark chocolate (70%)', amount: '200', unit: 'g' },
      { name: 'Butter', amount: '100', unit: 'g' },
      { name: 'Eggs', amount: '4', unit: 'large' },
      { name: 'Sugar', amount: '80', unit: 'g' },
      { name: 'Flour', amount: '40', unit: 'g' },
      { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
      { name: 'Cocoa powder', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, text: 'Preheat oven to 220°C. Butter and dust 4 ramekins with cocoa powder.' },
      { step: 2, text: 'Melt chocolate and butter together in a double boiler.', duration: 5 },
      { step: 3, text: 'Whisk eggs and sugar until pale. Fold in chocolate mixture.' },
      { step: 4, text: 'Fold in flour and vanilla. Pour into prepared ramekins.' },
      {
        step: 5,
        text: 'Bake for exactly 12 minutes. Invert onto plates and serve immediately.',
        duration: 12,
      },
    ],
    nutrition: { calories: 460, protein: 8, carbs: 48, fat: 28, fiber: 3 },
    tips: [
      'Timing is critical — 12 minutes gives a perfect molten center',
      'Can be prepared ahead and refrigerated before baking',
    ],
  },
  {
    id: '9',
    title: 'Greek Salad',
    description:
      'A refreshing classic with juicy tomatoes, crisp cucumbers, olives and creamy feta, dressed with olive oil and oregano.',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    cuisine: 'Mediterranean',
    difficulty: 'Easy',
    mealType: 'Lunch',
    dietTags: ['Vegetarian', 'Gluten-Free', 'Healthy'],
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    rating: 4.5,
    reviewCount: 654,
    calories: 220,
    author: 'Nikos Papadopoulos',
    ingredients: [
      { name: 'Tomatoes', amount: '4', unit: 'large' },
      { name: 'Cucumber', amount: '1', unit: 'large' },
      { name: 'Feta cheese', amount: '200', unit: 'g' },
      { name: 'Kalamata olives', amount: '100', unit: 'g' },
      { name: 'Red onion', amount: '1', unit: 'medium' },
      { name: 'Olive oil', amount: '4', unit: 'tbsp' },
      { name: 'Dried oregano', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      { step: 1, text: 'Chop tomatoes into wedges, slice cucumber into half-moons.' },
      { step: 2, text: 'Thinly slice red onion. Combine with tomatoes and cucumber.' },
      { step: 3, text: 'Add olives and top with a whole block of feta cheese.' },
      {
        step: 4,
        text: 'Drizzle generously with olive oil, sprinkle oregano and season with salt.',
      },
    ],
    nutrition: { calories: 220, protein: 8, carbs: 12, fat: 16, fiber: 3 },
    tips: [
      'Use the best quality olive oil you can find',
      "Don't crumble the feta — leave it in a block for authenticity",
    ],
  },
  {
    id: '10',
    title: 'Pad Thai',
    description:
      "Thailand's iconic stir-fried noodle dish with shrimp, tofu, crunchy peanuts and a perfectly balanced tamarind sauce.",
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    cuisine: 'Asian',
    difficulty: 'Medium',
    mealType: 'Dinner',
    dietTags: ['Dairy-Free', 'Gluten-Free'],
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    rating: 4.7,
    reviewCount: 1234,
    calories: 490,
    author: 'Mei Tanaka',
    ingredients: [
      { name: 'Rice noodles', amount: '200', unit: 'g' },
      { name: 'Shrimp', amount: '200', unit: 'g' },
      { name: 'Firm tofu', amount: '150', unit: 'g' },
      { name: 'Eggs', amount: '3', unit: 'large' },
      { name: 'Bean sprouts', amount: '100', unit: 'g' },
      { name: 'Tamarind paste', amount: '3', unit: 'tbsp' },
      { name: 'Fish sauce', amount: '2', unit: 'tbsp' },
      { name: 'Crushed peanuts', amount: '4', unit: 'tbsp' },
      { name: 'Green onions', amount: '3', unit: 'stalks' },
    ],
    instructions: [
      { step: 1, text: 'Soak rice noodles in warm water for 30 minutes.', duration: 30 },
      { step: 2, text: 'Mix tamarind, fish sauce, sugar and lime for the sauce.' },
      { step: 3, text: 'Stir-fry tofu and shrimp in a very hot wok until cooked.', duration: 5 },
      {
        step: 4,
        text: 'Push aside, scramble eggs, then add noodles and sauce. Toss everything.',
        duration: 5,
      },
      { step: 5, text: 'Finish with bean sprouts, green onions, and top with crushed peanuts.' },
    ],
    nutrition: { calories: 490, protein: 32, carbs: 56, fat: 16, fiber: 4 },
    tips: [
      'High heat is essential — use the hottest burner you have',
      "Don't overcrowd the wok or it will steam instead of fry",
    ],
  },
  {
    id: '11',
    title: 'Keto Bacon & Egg Cups',
    description:
      'Crispy bacon-lined muffin cups filled with eggs and cheese. The perfect low-carb, high-protein breakfast.',
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800',
    cuisine: 'American',
    difficulty: 'Easy',
    mealType: 'Breakfast',
    dietTags: ['Keto', 'Gluten-Free', 'Dairy-Free'],
    prepTime: 5,
    cookTime: 20,
    servings: 6,
    rating: 4.4,
    reviewCount: 543,
    calories: 210,
    author: 'Mike Johnson',
    ingredients: [
      { name: 'Bacon strips', amount: '12', unit: 'strips' },
      { name: 'Eggs', amount: '6', unit: 'large' },
      { name: 'Cheddar cheese', amount: '60', unit: 'g' },
      { name: 'Salt & pepper', amount: '', unit: 'to taste' },
      { name: 'Chives', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      {
        step: 1,
        text: 'Preheat oven to 190°C. Line a muffin tin with bacon strips forming a cup.',
      },
      { step: 2, text: 'Crack one egg into each bacon cup. Season with salt and pepper.' },
      { step: 3, text: 'Top with shredded cheese.' },
      { step: 4, text: 'Bake for 15–20 minutes depending on desired yolk firmness.', duration: 20 },
      { step: 5, text: 'Garnish with chives and serve immediately.' },
    ],
    nutrition: { calories: 210, protein: 14, carbs: 1, fat: 16, fiber: 0 },
    tips: ['Pre-cook bacon slightly if you like it extra crispy'],
  },
  {
    id: '12',
    title: 'Mango Lassi',
    description:
      'A cooling Indian yogurt drink blended with sweet ripe mangoes, cardamom and a pinch of saffron.',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800',
    cuisine: 'Indian',
    difficulty: 'Easy',
    mealType: 'Snack',
    dietTags: ['Vegetarian', 'Gluten-Free', 'Healthy'],
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    rating: 4.6,
    reviewCount: 432,
    calories: 180,
    author: 'Priya Sharma',
    ingredients: [
      { name: 'Ripe mango', amount: '2', unit: 'large' },
      { name: 'Plain yogurt', amount: '300', unit: 'g' },
      { name: 'Milk', amount: '100', unit: 'ml' },
      { name: 'Sugar', amount: '2', unit: 'tbsp' },
      { name: 'Cardamom', amount: '0.5', unit: 'tsp' },
      { name: 'Saffron', amount: '1', unit: 'pinch' },
    ],
    instructions: [
      { step: 1, text: 'Peel and cube mangoes. Place in blender.' },
      { step: 2, text: 'Add yogurt, milk, sugar, and cardamom. Blend until smooth.', duration: 2 },
      { step: 3, text: 'Bloom saffron in 1 tbsp warm milk for 5 minutes.' },
      { step: 4, text: 'Pour into glasses over ice. Drizzle saffron milk on top.' },
    ],
    nutrition: { calories: 180, protein: 7, carbs: 32, fat: 3, fiber: 2 },
    tips: ['Alphonso mangoes are the sweetest and most aromatic'],
  },
];
